chore: Update Dockerfile and docker-compose paths in build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -66,32 +66,30 @@ jobs:
         with:
           token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
 
-      - name: Install Docker Compose
-        run: |
-          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-          sudo chmod +x /usr/local/bin/docker-compose
-          docker-compose version
+      - name: SSH and Deploy on Droplet
+        uses: appleboy/ssh-action@v0.1.3
+        with:
+          host: ${{ secrets.DO_DUKE_IP }}
+          username: root
+          password: ${{ secrets.DUKE_ROOT_PASSWORD }}
+          script: |
+            # Install Docker Compose if not installed
+            if ! command -v docker-compose &> /dev/null; then
+              echo "Installing Docker Compose..."
+              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+              sudo chmod +x /usr/local/bin/docker-compose
+            fi
+            docker-compose version
 
-      - name: Deploy Application to Droplet
-        env:
-          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
-          SERVICE_NAME: ${{ github.event.inputs.service_name || 'duke' }}
-          DO_DUKE_IP: ${{ secrets.DO_DUKE_IP }}
-          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
-          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_SECRET }}
-          INFISICAL_PROJECT_ID: ${{ secrets.INFISICAL_PROJECT_ID }}
-        run: |
-          # Verify docker-compose.yml is present
-          echo "Checking for docker-compose.yaml..."
-          ls -l docker-compose.yaml || { echo "docker-compose.yaml not found!"; exit 1; }
+            # Verify docker-compose.yml is present
+            echo "Checking for docker-compose.yaml..."
+            ls -l docker-compose.yaml || { echo "docker-compose.yaml not found!"; exit 1; }
 
-          # Initialize Docker Swarm
-          echo "Initializing Docker Swarm..."
-          docker swarm init --advertise-addr $DO_DUKE_IP || echo "Docker Swarm already initialized."
+            # Initialize Docker Swarm
+            echo "Initializing Docker Swarm..."
+            docker swarm init --advertise-addr $DO_DUKE_IP || echo "Docker Swarm already initialized."
 
-          # Deploy using Docker Compose with explicit path
-          echo "Deploying with Docker Compose..."
-          docker-compose pull
-          docker-compose up -d
-
-          
+            # Deploy using Docker Compose
+            echo "Deploying with Docker Compose..."
+            docker-compose pull
+            docker-compose up -d
